title="OMERO Virtual Knowledge Graph"

[defaultTab]
query="""
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dc: <http://purl.org/dc/elements/1.1>
PREFIX omecore: <https://ld.openmicroscopy.org/core/>
PREFIX omekg: <https://ld.openmicroscopy.org/omekg#>
PREFIX obda: <https://w3id.org/obda/vocabulary#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?subject ?predicate ?object
WHERE {
  ?subject ?predicate ?object
}
limit 10
"""

[[tabGroups]]

name="Basic Queries"

[[tabGroups.tabs]]

name="All projects"
query="""
PREFIX omecore: <https://ld.openmicroscopy.org/core/>
PREFIX omens: <http://www.openmicroscopy.org/ns/default/>

SELECT *
WHERE {
  ?project a omecore:Project .
}
LIMIT 10
"""

[[tabGroups.tabs]]
name="Project/Dataset/Image hierarchy"
query="""
PREFIX prefix: <http://prefix.cc/>
PREFIX omecore: <https://ld.openmicroscopy.org/core/>
PREFIX omekg: <https://ld.openmicroscopy.org/omekg#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dcterms: <http://purl.org/dc/terms/>

select distinct * where {
  ?proj a omecore:Project ;
        dcterms:hasPart ?dataset .
  ?dataset a omecore:Dataset ;
           dcterms:hasPart ?image .
  ?image a omecore:Image .
}
order by ?project ?dataset ?image
limit 25

"""

[[tabGroups.tabs]]
name="Image map annotations"
query="""
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX omecore: <https://ld.openmicroscopy.org/core/>
SELECT distinct  * WHERE {
    ?img a omecore:Image;
         rdfs:label ?img_name;
         omecore:hasAnnotation ?annotation_obj.
  ?annotation_obj omecore:mapEntry [omecore:key ?key ; omecore:value ?value]
}
limit 20
"""

[[tabGroups.tabs]]
name="Map annotation keys"
query="""
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX omecore: <https://ld.openmicroscopy.org/core/>
SELECT distinct ?key WHERE {
    ?img a omecore:Image;
         rdfs:label ?img_name;
         omecore:hasAnnotation/omecore:mapEntry/omecore:key ?annotation_obj.
}
limit 20
"""

[[tabGroups.tabs]]
name="Images and (optional) tags"
query="""
PREFIX omecore: <https://ld.openmicroscopy.org/core/>
PREFIX omekg: <https://ld.openmicroscopy.org/omekg#>

  SELECT distinct ?img ?tag WHERE {
      ?img a omecore:Image; 
           omekg:tag_annotation_value ?tag .
   }
  order by ?img
  limit 10
"""

[[tabGroups]]
name="Aggregations"

[[tabGroups.tabs]]
name="Number of images grouped by dataset"
query="""
PREFIX omecore: <https://ld.openmicroscopy.org/core/>
PREFIX omekg: <https://ld.openmicroscopy.org/omekg#>
prefix dcterms: <http://purl.org/dc/terms/>

SELECT ?dataset (count(distinct ?img) as ?Nimg)
WHERE {
  ?img a omecore:Image ;
       ^dcterms:hasPart ?dataset . # Uses inverse property.
  ?dataset a omecore:Dataset .
}
group by ?dataset
order by desc(?Nimg) # Descending sort by number of images.
"""

[[tabGroups.tabs]]
name="Total number of images"
query="""
PREFIX omecore: <https://ld.openmicroscopy.org/core/>
PREFIX omekg: <https://ld.openmicroscopy.org/omekg#>
PREFIX omens: <http://www.openmicroscopy.org/ns/default/>

SELECT (count(distinct ?img) as ?Nimg)
WHERE {
  ?img a omecore:Image ;
}
"""

[[tabGroups]]
name="Graph exploration"

[[tabGroups.tabs]]
name="Types/Classes"
query="""
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?class
WHERE {
  ?subject a ?class .
}
order by ?class
"""

[[tabGroups.tabs]]
name="Distinct properties per class/type"
query="""
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?class ?property
WHERE {
  ?subject a ?class ;
           ?property ?val .
}
order by ?class
"""

[[tabGroups]]
name="Tests"

[[tabGroups.tabs]]
name="Total number of images"
query="""
PREFIX omecore: <https://ld.openmicroscopy.org/core/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

ask where {
  {
    select (count(?img) as ?nimg) where {
      ?img a omecore:Image .}
  }
  filter(?nimg="1560"^^xsd:integer)
}
"""